services:
  backend:
    build: ./backend
    container_name: task-management-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    environment:
      - UPLOAD_PATH=/app/uploads
    depends_on:
      - mongo
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: task-management-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: task-management-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=task-management

volumes:
  uploads:
  mongodb_data:

networks:
  app-network: